version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: run_trainer_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: coach_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: run_trainer_api
    restart: always
    environment:
      DATABASE_URL: postgresql+asyncpg://user:pass@db:5432/coach_db
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: run_trainer_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      # - web # Пока закомментируй, если папку web еще не создал

volumes:
  postgres_data: